"""tablename

Revision ID: 8a915d5b48ee
Revises: e4e3b63aeee6
Create Date: 2022-11-04 11:54:30.074253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a915d5b48ee'
down_revision = 'e4e3b63aeee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('SimplePerson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SimplePerson',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('bio', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('simple_people')
    # ### end Alembic commands ###
