"""tablename

Revision ID: e4e3b63aeee6
Revises: 63ab990a4436
Create Date: 2022-11-04 11:47:53.846787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e3b63aeee6'
down_revision = '63ab990a4436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SimplePerson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('simple_person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('bio', sa.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('SimplePerson')
    # ### end Alembic commands ###
